services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:22
    environment:
      NX_DAEMON_SOCKET_DIR: '/test'
      NX_DAEMON: true
    volumes:
      - ../:/workspaces:cached
      # Mount local tmp to container
      - ~/tmp:/tmp/local
      - ~/.ssh:/home/node/.ssh:ro
    network_mode: service:db
    command: sleep infinity

  db:
    container_name: playstation_db
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
