services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:22
    volumes:
      - ../:/workspaces:cached
      # SSH key for git
      - ~/.ssh:/home/node/.ssh:ro
      # Improve disk performance (only for folders that are written frequently)
      # Ref: https://code.visualstudio.com/remote/advancedcontainers/improve-performance
      - node_modules:/workspaces/node_modules
      - nx-volumn:/workspaces/.nx
      - api-dist:/workspaces/apps/api/dist
    network_mode: service:db
    command: sleep infinity

  db:
    container_name: playstation_db
    image: postgres:17.5-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $DB_USER']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  node_modules:
  api-dist:
  nx-volumn:
